<a href="https://colab.research.google.com/github/sumedhman/deep_learnig/blob/master/list_vs_np_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
l =[1,2,3]


In [5]:
a=np.array([1,2,3])
for i in l:
  print(i)

1
2
3


In [6]:
for e in a:
  print(e)

1
2
3


In [7]:
l.append(4)
l

[1, 2, 3, 4]

In [8]:
a.append(4)  #no method availble for append in np arrary

AttributeError: ignored

In [9]:
l=l+[5]
l


[1, 2, 3, 4, 5]

In [10]:
a=a+[4,5]
a

ValueError: ignored

In [11]:
l2= []
for e in l:
  l2.append(e+e)
l2

[2, 4, 6, 8, 10]

In [12]:
a+a


array([2, 4, 6])

In [13]:
2*a

array([2, 4, 6])

In [14]:
2*l

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [19]:
l2=[]
for e in l:
  l2.append(e*e)
l2


[1, 4, 9]

In [20]:
a **2

array([1, 4, 9])

In [22]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [23]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [24]:
np.exp(a)  #exponential

array([ 2.71828183,  7.3890561 , 20.08553692])

In [0]:
#list is for elment access one by one
#np array access element as vector and it is easy to work on no of number as compared to list.
#so that np array is fast and work fast on vector.