<a href="https://colab.research.google.com/github/sumedhman/deep_learnig/blob/master/vector_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
m= np.array([[1,2],[3,4]])
l=[[1,2],[3,4]]
l[0][0]
m[0]

array([1, 2])

In [5]:
m[0][0]

1

In [6]:
m[0,0]

1

In [7]:
m2=np.matrix([[1,2],[3,4]])
m2

matrix([[1, 2],
        [3, 4]])

In [21]:
a=np.array(m2)
a

array([[1, 2],
       [3, 4]])

In [10]:
#vector is one dimensional array and matrix is 2 d array
a.T

array([[1, 3],
       [2, 4]])

In [11]:
np.array([1,2,3])

array([1, 2, 3])

In [12]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
z=np.zeros([10,10])
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
o=np.ones((10,10))
o


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
#generate the random no.
r=np.random.random((10,10))
r

array([[0.72110074, 0.86746728, 0.63436556, 0.5963085 , 0.05693   ,
        0.92076989, 0.05083749, 0.85709197, 0.79394181, 0.22307146],
       [0.6067964 , 0.82427914, 0.12788979, 0.66996349, 0.81363552,
        0.07038883, 0.12204274, 0.82853319, 0.68238997, 0.82209842],
       [0.09410223, 0.52570557, 0.48798167, 0.33564979, 0.85434314,
        0.12986721, 0.83362781, 0.72450195, 0.18310727, 0.46444228],
       [0.54211439, 0.59434353, 0.30880458, 0.65258538, 0.65676038,
        0.19522094, 0.59806606, 0.47169603, 0.529018  , 0.67495835],
       [0.68636485, 0.75621863, 0.2595683 , 0.46142016, 0.26269658,
        0.61021467, 0.15033264, 0.48738249, 0.23195054, 0.4994898 ],
       [0.61723544, 0.67868463, 0.08093011, 0.58070883, 0.69438388,
        0.39949516, 0.4822496 , 0.11057343, 0.14975552, 0.82346797],
       [0.93546241, 0.91905109, 0.08349533, 0.56687525, 0.53292729,
        0.06519035, 0.36027817, 0.8093809 , 0.76523264, 0.1456357 ],
       [0.60569027, 0.13059925, 0.6654963

In [17]:
g= np.random.randn(10,10)
g

array([[ 1.50574898,  0.26279465, -0.16944762, -1.2287913 , -0.38947171,
        -0.14677357,  1.11042088,  2.00858576,  0.90063221, -1.64617921],
       [ 0.14549009,  2.17682061,  0.93839852, -1.27396127, -1.95352991,
         0.29314371,  0.71500337, -0.69954258, -1.51471976,  0.39760154],
       [-1.13387873,  0.33703865, -0.09033834, -0.43708691,  0.92992359,
        -1.15730687,  0.8023396 , -1.17820801, -1.41713242,  1.02489996],
       [ 1.26348246, -0.22065075, -0.51311468,  0.99284032,  0.79123142,
        -0.76328781,  0.73753403, -1.42024195, -1.52891213, -0.81895731],
       [-0.75109136,  0.08702015,  0.45627375,  0.48367765,  0.44546981,
         1.3858155 , -0.13070798,  0.40148821, -0.81945374, -0.56916997],
       [-2.69353694, -0.9891192 , -0.82878742,  0.84437119,  0.6726762 ,
         1.40542274, -0.27996449, -0.34647632, -0.02180865, -0.28322418],
       [-1.61502023, -1.33098459, -0.77789342,  0.20059572,  0.11019724,
         1.53223752, -2.26614318,  0.64528814

In [18]:
g.mean()

-0.07534238906474248

In [19]:
g.var()

1.072016867783941

In [22]:
#matrix more operation
ainvers =np.linalg.inv(a)
ainvers


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [23]:
ainvers.dot(a)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [24]:
a.dot(ainvers)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [25]:
np.linalg.det(a)

-2.0000000000000004

In [26]:
np.diag(a)

array([1, 4])

In [27]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [28]:
e =np.array([1,2])
f =np.array([3,4])
np.outer(e,f)

array([[3, 4],
       [6, 8]])

In [29]:
np.inner(e,f)

11

In [30]:
e.dot(f)  # output as same as above 

11

In [32]:
np.trace(e)

ValueError: ignored